apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embedding-results
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
