apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: era5-2025-pretrain
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
