apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: era5-summer-soil-moisture
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 700Gi
