apiVersion: v1
kind: Pod
metadata:
  name: era5-many-connect-shell
spec:
  restartPolicy: Never
  containers:
  - name: shell
    image: puschb/aurora-dev:latest
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
    - name: data
      mountPath: /mnt/data
    resources:
      requests:
        memory: 4Gi
        cpu: "1"
      limits:
        memory: 4Gi
        cpu: "1"
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: era5-summer-data-many-connect
